### ISSUE TITLE
Unbundling various libraries

### ISSUE THREAD

**Issue by sanjayankur31** [CNS-OIST/STEPS#15]
Hello,

I am working on making [STEPS available in NeuroFedora](https://pagure.io/neuro-sig/NeuroFedora/issue/210). While auditing the source, I see that a couple of libraries are bundled. Is this necessary? Would it be possible to remove these bundles or provide a mechanism that permis the use of system installations of these libraries?

- [easyloggingpp](https://github.com/muflihun/easyloggingpp/tree/b7b4cbf8de1c7a85c45b7e17cdaff95b256b18a8): single header library so relatively easy to unbundle, can be down downstream
- [Random123](https://github.com/CNS-OIST/STEPS/tree/master/src/third_party/Random123): not developed any more but still easy to unbundle and can also be done downstream. Please note that [Random123 does not support all architectures](https://github.com/CNS-OIST/STEPS/blob/master/src/third_party/Random123/features/gccfeatures.h#L37), and therefore using it also implies that STEPS does not support all architectures. (Neuron, which also uses Random123 has [similar constraints](https://github.com/neuronsimulator/nrn/issues/114))
- [cvode](https://github.com/CNS-OIST/STEPS/tree/master/src/third_party/cvode-2.6.0): outdated version of SUNDIALS, as the current version is 3.2.x. One needs to check if STEPS compile with the newer version, so unbundling this is potentially a more involved task.
- [superLU_dist](https://github.com/CNS-OIST/STEPS/tree/master/src/third_party/superlu_dist-4.1): outdated version of SuperLU_dist as the current version is 5.2.x. Here too, one needs to check if STEPS will compile with the newer version, and that makes this a more involved task also.

I can help with testing with the newer libraries, since they are available in Fedora. However, it would be nice if STEPS did not bundle older versions of software, or if it did it bundled newer versions that contain fixes and enhancements. If a mechanism to enable the use of system versions of libraries can be included in the CMake files, that would be awesome.

**Comment by WeiliangChenOIST** [comment]
Hi @sanjayankur31 , thanks for the contact and the testing. 

I think all these are doable and we will put them into consideration for our next release. This will take some time though (our current plan is to release it by Apr this year) as we are also working on a major modernization of our code. 

Regarding Random123, STEPS also has another random number generator implementing mt19937. At the moment we don't have the detection and the switch between these two but it should be easy to do in the cmake file.

**Comment by sanjayankur31** [comment]
:+1: That sounds great. I'll wait for the new release to make it available in NeuroFedora. Cheers!

**Comment by mesimulator** [comment]
Dear STEPS Support, 

I am just starting to use STEPS for my research. I question is : 
Can we install STEPS on a local machine (Desktop computer) ? I mean will it take 
a lot of space / slow down my desktop ? 

In that case, I should install it on computing clusters ? 

Please let me know your suggestions on this. 

Thanks in anticipation,

**Comment by sanjayankur31** [comment]
@mesimulator : could you open a new issue for your question please? As you can see this ticket is specifically about unbundling libraries and it'd be most useful to have only relevant comments here. :)

Thanks very much.

**Comment by WeiliangChenOIST** [comment]
resolved in #19
