### ISSUE TITLE
Problem in installing steps

### ISSUE THREAD

**Issue by Vinoth461996** [CNS-OIST/STEPS#17]
Hi,
I tried installing STEPS through source code. the first command "cd STEPS" is itself, and then i assumed "STEPS-master" is the folder mentioned. Then, while entering "cmake..", it is showing  two errors, for which i have attached the screenshot also.

Please help me resolve it.

![Screenshot from 2019-04-03 10:17:01](https://user-images.githubusercontent.com/49222274/55453848-340e1080-55fb-11e9-9d0c-91e1b08984ba.png)

**Comment by WeiliangChenOIST** [comment]
Hi Vinoth, 
If you are using Ubuntu or similar system, please try to install pstec using the command below, then compile STEPS again.

`sudo apt-get install petsc-dev`

**Comment by Vinoth461996** [comment]
Thanks. I tried it. Still it is showing the same error

**Comment by WeiliangChenOIST** [comment]
Could you please provide the information about your system? I will see if I can reproduce the issue.

**Comment by tristan0x** [comment]
Hello @Vinoth461996 
First let me thanks for your interests in STEPS.
Can you please follow the instructions to install the requirements in the *Requirements* section of the README, i.e:

```
sudo apt-get install g++ gcc cmake libopenblas-dev libmpich-dev python-numpy cython python-scipy
```

If you "just" want to try STEPS, and do not need to run MPI jobs in an HPC cluster, I suggest you to use the STEPS [Docker image](https://github.com/CNS-OIST/STEPS_Docker)

**Comment by Vinoth461996** [comment]
> Hello @Vinoth461996
> First let me thank you for your interests in STEPS.
> Can you please follow the instructions to install the requirements in the _Requirements_ section of the README, i.e:
> 
> ```
> sudo apt-get install g++ gcc cmake libopenblas-dev libmpich-dev python-numpy cython python-scipy
> ```
> 
> If you "just" want to try STEPS, and do not need to run MPI jobs in an HPC cluster, I suggest you to use the STEPS [Docker image](https://github.com/CNS-OIST/STEPS_Docker)

I am having problems in installing cmake only

**Comment by Vinoth461996** [comment]
> Could you please provide the information about your system? I will see if I can reproduce the issue.

I am attaching the information about my sytem
![Screenshot from 2019-04-03 11:25:22](https://user-images.githubusercontent.com/49222274/55477765-8d943080-5637-11e9-9ed3-157e1e91f003.png)

**Comment by tristan0x** [comment]
Ubuntu dropped support of this distribution at the beginning of this month. Can you try with a more recent version of 

> > Hello @Vinoth461996
> > First let me thank you for your interests in STEPS.
> > Can you please follow the instructions to install the requirements in the _Requirements_ section of the README, i.e:
> > ```
> > sudo apt-get install g++ gcc cmake libopenblas-dev libmpich-dev python-numpy cython python-scipy
> > ```
> > If you "just" want to try STEPS, and do not need to run MPI jobs in an HPC cluster, I suggest you to use the STEPS [Docker image](https://github.com/CNS-OIST/STEPS_Docker)
> 
> I am having problems in installing cmake only

Have you tried to install the packages I mentioned?

```
sudo apt-get install g++ gcc cmake libopenblas-dev libmpich-dev python-numpy cython python-scipy
```

**Comment by tristan0x** [comment]
Ubuntu 14.04 LTS reaches end of life [this month](https://wiki.ubuntu.com/Releases)
Can't you use a more recent distribution?

**Comment by Vinoth461996** [comment]
OK. Thanks a lot. I will update and try again

**Comment by WeiliangChenOIST** [comment]
just tested it on a 14.04 virtual machine but cannot reproduce the error.
Looks like for some reason it cannot find openblas.

@Vinoth461996 have you tried to install the required packages as suggested by @tristan0x and recompile STEPS?

`sudo apt-get install g++ gcc cmake libopenblas-dev libmpich-dev python-numpy cython python-scipy`

If it still has problem, please copy the terminal output to us for analysis.

```
wchen@wchen-VirtualBox:~/STEPS/build$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.6 LTS
Release:	14.04
Codename:	trusty
wchen@wchen-VirtualBox:~/STEPS/build$ rm -rf *
wchen@wchen-VirtualBox:~/STEPS/build$ cmake ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Generating debug symbols: -ggdb3
-- Looking for strip utility
-- Looking for strip utility - found
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Found PythonInterpLibs: /usr/lib/python2.7/config-i386-linux-gnu/libpython2.7.so  
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found MPI_C: /usr/lib/i386-linux-gnu/libmpich.so;/usr/lib/i386-linux-gnu/libopa.so;/usr/lib/i386-linux-gnu/libmpl.so;/usr/lib/i386-linux-gnu/librt.so;/usr/lib/libcr.so;/usr/lib/i386-linux-gnu/libpthread.so  
-- Found MPI_CXX: /usr/lib/i386-linux-gnu/libmpichcxx.so;/usr/lib/i386-linux-gnu/libmpich.so;/usr/lib/i386-linux-gnu/libopa.so;/usr/lib/i386-linux-gnu/libmpl.so;/usr/lib/i386-linux-gnu/librt.so;/usr/lib/libcr.so;/usr/lib/i386-linux-gnu/libpthread.so  
-- Could NOT find PETSC (missing:  PETSC_LIBRARIES PETSC_INCLUDE_DIRS) 
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- A library with BLAS API found.
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- PYTHON packages being installed to /usr/lib/python2.7/dist-packages. To change use -DPYTHON_INSTALL_PREFIX=<dir>
-- Found Cython: /usr/bin/cython (found suitable version "0.29.6", minimum required is "0.25.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wchen/STEPS/build

```

**Comment by Vinoth461996** [comment]
![image](https://user-images.githubusercontent.com/49222274/55795028-74322f00-5ae4-11e9-8634-757b689f5ec8.png)
Hi,
I have updated my ubuntu. Now when i am trying with make command, this issue arises. Can you help with this?

**Comment by tristan0x** [comment]
1. Which version of ubuntu are you using. Can you print here the output of the command `lsb_release -a`?
1. it seems the `python-dev` package is missing. Can you please install it and try to rebuild?

**Comment by Vinoth461996** [comment]
![image](https://user-images.githubusercontent.com/49222274/55872287-3dbee780-5baa-11e9-8c4a-4a788c61b4d9.png)
python-dev is insatlled already. and I have attached image for my ubuntu version also.

**Comment by tristan0x** [comment]
Could you please send us the `CMakeCache.txt` file that should be in your CMake build directory?

**Comment by Vinoth461996** [comment]
[CMakeCache.txt](https://github.com/CNS-OIST/STEPS/files/3063400/CMakeCache.txt)

**Comment by tristan0x** [comment]
From the `PYTHON_EXECUTABLE` CMake variable, it seems python 3 is used.
Can you please run the following commands?

```
cd build
cmake -DPYTHON_EXECUTABLE=/usr/bin/python2.7 .
make -j
```

**Comment by Vinoth461996** [comment]
![image](https://user-images.githubusercontent.com/49222274/55875001-8ded7800-5bb1-11e9-9177-c311ec622cac.png)
Thanks , That helped me get through it. But , this error is showing up now. please help me rectify it.

**Comment by tristan0x** [comment]
THat's good news. Can you please share the full build output?

**Comment by Vinoth461996** [comment]
inoth@Vinoth:~/STEPS/build$ sudo make install
[sudo] password for vinoth: 
[ 81%] Built target libsteps-obj
[ 82%] Built target libsteps
[ 83%] Built target libsteps_static
[ 84%] Built target cysteps
[ 84%] Built target steps_package_pure_py
[ 86%] Built target gtest
[ 87%] Built target gtest_main
[ 89%] Built target test_rng
[ 91%] Built target test_tetmesh
[ 92%] Built target test_membership
[ 93%] Built target test_point3d
[ 95%] Built target test_bbox
[ 96%] Built target test_checkid
[ 98%] Built target test_bdsystem
[ 99%] Built target test_sample
[100%] Built target test_small_binomial
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /steps/cysteps.so
running build
running build_py
running install
running install_lib
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/visual/__init__.py -> steps/visual
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/visual/SimDisplay.py -> steps/visual
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/visual/Plotting.py -> steps/visual
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/visual/StaticComponent.py -> steps/visual
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/visual/DynamicComponent.py -> steps/visual
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/visual/Control.py -> steps/visual
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/visual/Colors.py -> steps/visual
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/visual/PartitionViewer.py -> steps/visual
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/__init__.py -> steps
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/model.py -> steps
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/rng.py -> steps
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/quiet.py -> steps
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/morph_support.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/__init__.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/geom_decompose.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/steps_cubit.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/matlab_support/__init__.py -> steps/utilities/matlab_support
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/matlab_support/simulate.py -> steps/utilities/matlab_support
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/matlab_support/matlab_parser.py -> steps/utilities/matlab_support
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/matlab_support/event_parser.py -> steps/utilities/matlab_support
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/meshio.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/meshctrl.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/sbml.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/steps_shadow.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/metis_support.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/cubit_support.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/geom.py -> steps
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/mpi/__init__.py -> steps/mpi
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/mpi/solver.py -> steps/mpi
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/solver.py -> steps
byte-compiling steps/visual/__init__.py to __init__.pyc
byte-compiling steps/visual/SimDisplay.py to SimDisplay.pyc
byte-compiling steps/visual/Plotting.py to Plotting.pyc
byte-compiling steps/visual/StaticComponent.py to StaticComponent.pyc
byte-compiling steps/visual/DynamicComponent.py to DynamicComponent.pyc
byte-compiling steps/visual/Control.py to Control.pyc
byte-compiling steps/visual/Colors.py to Colors.pyc
byte-compiling steps/visual/PartitionViewer.py to PartitionViewer.pyc
byte-compiling steps/__init__.py to __init__.pyc
byte-compiling steps/model.py to model.pyc
byte-compiling steps/rng.py to rng.pyc
byte-compiling steps/quiet.py to quiet.pyc
byte-compiling steps/utilities/morph_support.py to morph_support.pyc
byte-compiling steps/utilities/__init__.py to __init__.pyc
byte-compiling steps/utilities/geom_decompose.py to geom_decompose.pyc
byte-compiling steps/utilities/steps_cubit.py to steps_cubit.pyc
byte-compiling steps/utilities/matlab_support/__init__.py to __init__.pyc
byte-compiling steps/utilities/matlab_support/simulate.py to simulate.pyc
byte-compiling steps/utilities/matlab_support/matlab_parser.py to matlab_parser.pyc
byte-compiling steps/utilities/matlab_support/event_parser.py to event_parser.pyc
byte-compiling steps/utilities/meshio.py to meshio.pyc
byte-compiling steps/utilities/meshctrl.py to meshctrl.pyc
byte-compiling steps/utilities/sbml.py to sbml.pyc
byte-compiling steps/utilities/steps_shadow.py to steps_shadow.pyc
byte-compiling steps/utilities/metis_support.py to metis_support.pyc
byte-compiling steps/utilities/cubit_support.py to cubit_support.pyc
byte-compiling steps/geom.py to geom.pyc
byte-compiling steps/mpi/__init__.py to __init__.pyc
byte-compiling steps/mpi/solver.py to solver.pyc
byte-compiling steps/solver.py to solver.pyc
running install_egg_info
Creating 
error: [Errno 2] No such file or directory: ''

**Comment by Vinoth461996** [comment]
Hi,
This is what i am getting when i am rebuilding using the command "cmake .."


-- Generating debug symbols: -ggdb3
-- Looking for strip utility
-- Looking for strip utility - found
-- Could NOT find PythonInterpLibs (missing: PYTHON_LIBRARIES) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS) 
-- Could NOT find MPI (missing: MPI_CXX_FOUND) (found version "3.1")
CMake Warning at CMakeLists.txt:126 (message):
  Building without PETSC.  If desired enable finding MPI libs as well!


-- A library with BLAS API found.
-- PYTHON packages being installed to . To change use -DPYTHON_INSTALL_PREFIX=<dir>
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vinoth/STEPS/build

**Comment by WeiliangChenOIST** [comment]
@Vinoth461996 Sorry for the late reply. Looks like it has problem finding the install path. Can you provide the output of the following command please?

```
/usr/bin/python2.7 -c "import sys;print sys.path"
```

**Comment by Vinoth461996** [comment]
Got it. Installed it. Thanks for the constant support
