### ISSUE TITLE
problem in installing STEPS

### ISSUE THREAD

**Issue by Vinoth461996** [CNS-OIST/STEPS#18]
vinoth@Vinoth:~/STEPS/build$ sudo make install
[sudo] password for vinoth: 
[ 81%] Built target libsteps-obj
[ 82%] Built target libsteps
[ 83%] Built target libsteps_static
[ 84%] Built target cysteps
[ 84%] Built target steps_package_pure_py
[ 86%] Built target gtest
[ 87%] Built target gtest_main
[ 89%] Built target test_rng
[ 91%] Built target test_tetmesh
[ 92%] Built target test_membership
[ 93%] Built target test_point3d
[ 95%] Built target test_bbox
[ 96%] Built target test_checkid
[ 98%] Built target test_bdsystem
[ 99%] Built target test_sample
[100%] Built target test_small_binomial
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /steps/cysteps.so
running build
running build_py
running install
running install_lib
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/visual/__init__.py -> steps/visual
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/visual/SimDisplay.py -> steps/visual
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/visual/Plotting.py -> steps/visual
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/visual/StaticComponent.py -> steps/visual
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/visual/DynamicComponent.py -> steps/visual
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/visual/Control.py -> steps/visual
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/visual/Colors.py -> steps/visual
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/visual/PartitionViewer.py -> steps/visual
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/__init__.py -> steps
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/model.py -> steps
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/rng.py -> steps
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/quiet.py -> steps
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/morph_support.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/__init__.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/geom_decompose.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/steps_cubit.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/matlab_support/__init__.py -> steps/utilities/matlab_support
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/matlab_support/simulate.py -> steps/utilities/matlab_support
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/matlab_support/matlab_parser.py -> steps/utilities/matlab_support
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/matlab_support/event_parser.py -> steps/utilities/matlab_support
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/meshio.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/meshctrl.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/sbml.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/steps_shadow.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/metis_support.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/utilities/cubit_support.py -> steps/utilities
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/geom.py -> steps
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/mpi/__init__.py -> steps/mpi
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/mpi/solver.py -> steps/mpi
copying /home/vinoth/STEPS/build/lib.linux-x86_64-2.7/steps/solver.py -> steps
byte-compiling steps/visual/__init__.py to __init__.pyc
byte-compiling steps/visual/SimDisplay.py to SimDisplay.pyc
byte-compiling steps/visual/Plotting.py to Plotting.pyc
byte-compiling steps/visual/StaticComponent.py to StaticComponent.pyc
byte-compiling steps/visual/DynamicComponent.py to DynamicComponent.pyc
byte-compiling steps/visual/Control.py to Control.pyc
byte-compiling steps/visual/Colors.py to Colors.pyc
byte-compiling steps/visual/PartitionViewer.py to PartitionViewer.pyc
byte-compiling steps/__init__.py to __init__.pyc
byte-compiling steps/model.py to model.pyc
byte-compiling steps/rng.py to rng.pyc
byte-compiling steps/quiet.py to quiet.pyc
byte-compiling steps/utilities/morph_support.py to morph_support.pyc
byte-compiling steps/utilities/__init__.py to __init__.pyc
byte-compiling steps/utilities/geom_decompose.py to geom_decompose.pyc
byte-compiling steps/utilities/steps_cubit.py to steps_cubit.pyc
byte-compiling steps/utilities/matlab_support/__init__.py to __init__.pyc
byte-compiling steps/utilities/matlab_support/simulate.py to simulate.pyc
byte-compiling steps/utilities/matlab_support/matlab_parser.py to matlab_parser.pyc
byte-compiling steps/utilities/matlab_support/event_parser.py to event_parser.pyc
byte-compiling steps/utilities/meshio.py to meshio.pyc
byte-compiling steps/utilities/meshctrl.py to meshctrl.pyc
byte-compiling steps/utilities/sbml.py to sbml.pyc
byte-compiling steps/utilities/steps_shadow.py to steps_shadow.pyc
byte-compiling steps/utilities/metis_support.py to metis_support.pyc
byte-compiling steps/utilities/cubit_support.py to cubit_support.pyc
byte-compiling steps/geom.py to geom.pyc
byte-compiling steps/mpi/__init__.py to __init__.pyc
byte-compiling steps/mpi/solver.py to solver.pyc
byte-compiling steps/solver.py to solver.pyc
running install_egg_info
Creating 
error: [Errno 2] No such file or directory: ''

**Comment by Vinoth461996** [comment]
Hi,
This is what i am getting when i am rebuilding using the command "cmake .."


-- Generating debug symbols: -ggdb3
-- Looking for strip utility
-- Looking for strip utility - found
-- Could NOT find PythonInterpLibs (missing: PYTHON_LIBRARIES) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_WORKS) 
-- Could NOT find MPI (missing: MPI_CXX_FOUND) (found version "3.1")
CMake Warning at CMakeLists.txt:126 (message):
  Building without PETSC.  If desired enable finding MPI libs as well!


-- A library with BLAS API found.
-- PYTHON packages being installed to . To change use -DPYTHON_INSTALL_PREFIX=<dir>
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vinoth/STEPS/build

**Comment by WeiliangChenOIST** [comment]
close this issue as it is a duplication of #17
