### ISSUE TITLE
Consider renaming repository, removing postfix "_Release"

### ISSUE THREAD

**Issue by mcraveiro** [CNS-OIST/STEPS#2]
Hi STEPS developers,

I think the "_Release" postfix is a bit confusing. Presumably the name of the product is STEPS right? i.e. what's the difference between STEPS and STEPS_Release? Presumably you want to make some kind of separation between your internal repository with full version history and a "release" repository? Even so I'd consider not calling the GitHub repository STEPS_Release, since all the forks will also be called STEPS_Release and so on.

Cheers

Marco

**Comment by WeiliangChenOIST** [comment]
Hi Marco,

Good point. I've rearranged the name of the repositories so that STEPS is now the release repository. Please refork it again.
