### ISSUE TITLE
Problem installing on Ubuntu

### ISSUE THREAD

**Issue by sepinouda** [CNS-OIST/STEPS#20]
Hi,

I am trying to install STEPS on Ubuntu-16.04-Cuda. 

after using cmake -DBLAS_LIBRARIES=/home/cloud-user/amber/miniconda/lib/  -DLAPACK_LIBRARIES=/home/cloud-user/amber/miniconda/lib/ ..

I get the following, I was wondering if you know where the issue is.

-- Generating debug symbols: -ggdb3
-- Looking for strip utility
-- Looking for strip utility - found
-- A library with BLAS API found.
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP C flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [ ]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-fopenmp=libomp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [/openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-Qopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-openmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-xopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [+Oopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-qsmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Try OpenMP CXX flag = [-mp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Failed
-- Could NOT find OpenMP (missing:  OpenMP_C_FLAGS OpenMP_CXX_FLAGS) 
-- PYTHON packages being installed to /usr/lib/python2.7/dist-packages. To change use -DPYTHON_INSTALL_PREFIX=<dir>
-- Configuring done
WARNING: Target "cysteps" requests linking to directory "/home/cloud-user/amber/miniconda/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "cysteps" requests linking to directory "/home/cloud-user/amber/miniconda/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "libsteps" requests linking to directory "/home/cloud-user/amber/miniconda/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "libsteps" requests linking to directory "/home/cloud-user/amber/miniconda/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_membership" requests linking to directory "/home/cloud-user/amber/miniconda/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_petscsystem" requests linking to directory "/home/cloud-user/amber/miniconda/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_tetmesh" requests linking to directory "/home/cloud-user/amber/miniconda/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_point3d" requests linking to directory "/home/cloud-user/amber/miniconda/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_checkid" requests linking to directory "/home/cloud-user/amber/miniconda/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_rng" requests linking to directory "/home/cloud-user/amber/miniconda/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_sample" requests linking to directory "/home/cloud-user/amber/miniconda/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_bbox" requests linking to directory "/home/cloud-user/amber/miniconda/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_small_binomial" requests linking to directory "/home/cloud-user/amber/miniconda/lib/".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "test_bdsystem" requests linking to directory "/home/cloud-user/amber/miniconda/lib/".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: /home/cloud-user/STEPS/build

Thank you.

**Comment by WeiliangChenOIST** [comment]
Hi, OpenMP is not necessary for the compiling so that is fine. But `-DBLAS_LIBRARIES=/home/cloud-user/amber/miniconda/lib/ -DLAPACK_LIBRARIES=/home/cloud-user/amber/miniconda/lib/` should point to the library file rather than the directory.

**Comment by sepinouda** [comment]
Do you know the name of the files?

**Comment by WeiliangChenOIST** [comment]
try install openblas with `conda install -c anaconda openblas`, and use `cmake ..` to see if it can be found automatically. Don't forget to delete the old build files first.

**Comment by pauloburke** [comment]
@sepinouda I pointed to the file "libcblas.so" and it seems to work.
