### ISSUE TITLE
GPL2 vs. GPL3 license issues

### ISSUE THREAD

**Issue by musicinmybrain** [CNS-OIST/STEPS#28]
Based on `LICENSE.md`, it appears that the overall license of STEPS is intended to be [GPL-2.0-only](https://spdx.org/licenses/GPL-2.0-only.html).

However, the metadata for the Python packages (wrongly?) indicates a license of [GPL-3.0-only](https://spdx.org/licenses/GPL-3.0-only.html):

https://github.com/CNS-OIST/STEPS/blob/a910839e5a19a0d95eeb113b522fa6d3627efefd/pysteps/setup.py#L63

https://github.com/CNS-OIST/STEPS/blob/a910839e5a19a0d95eeb113b522fa6d3627efefd/pysteps/cmake_setup.py.in#L37

A number of source files within `pysteps` explicitly contradict this, e.g:

https://github.com/CNS-OIST/STEPS/blob/a910839e5a19a0d95eeb113b522fa6d3627efefd/pysteps/steps/__init__.py#L12-L14

Furthermore, a few source files really are marked with a license of [GPL-3.0-or-later](https://spdx.org/licenses/GPL-3.0-or-later.html):

https://github.com/CNS-OIST/STEPS/blob/a910839e5a19a0d95eeb113b522fa6d3627efefd/src/steps/geom/sdiffboundary.hpp#L10-L13

https://github.com/CNS-OIST/STEPS/blob/a910839e5a19a0d95eeb113b522fa6d3627efefd/src/steps/solver/sdiffboundarydef.hpp#L10-L13

https://github.com/CNS-OIST/STEPS/blob/a910839e5a19a0d95eeb113b522fa6d3627efefd/src/steps/mpi/tetopsplit/sdiffboundary.hpp#L10-L13

https://github.com/CNS-OIST/STEPS/blob/a910839e5a19a0d95eeb113b522fa6d3627efefd/src/steps/mpi/tetopsplit/sdiffboundary.cpp#L10-L13

This is problematic because [GPLv2 and GPLv3 are not compatible](https://www.gnu.org/licenses/gpl-faq.html#v2v3Compatibility).

**Comment by WeiliangChenOIST** [comment]
Thanks for the notice. We will update the license in the next update.

**Comment by musicinmybrain** [comment]
Thanks for taking a look at this!
