### ISSUE TITLE
Is there a way to create specific structure from zero within STEP4?

### ISSUE THREAD

**Issue by zhaolun7** [CNS-OIST/STEPS#33]
I am looking the manual web pages(https://steps.sourceforge.net/manual/) and try to find a way to create specific structure like Purkinje cells, but It seems like STEPS is focused on the reaction details, which means that it need some other softwares to create a structure and export a file for loading into STEPS. 
Is this understanding correct or am I missing something?

**Comment by WeiliangChenOIST** [comment]
Dear @zhaolun7 
There are multiple solutions depending on what morphology you want to reconstruct and what source data you have. For purkinje cell data from light microscopic imaging (.swc), you can use https://github.com/CNS-OIST/SWCTetMesher. We've also gathered some useful meshing tools in https://github.com/CNS-OIST/meshing, which may be helpful.

**Comment by WeiliangChenOIST** [comment]
In general, yes you will need other meshing tools to generate the mesh, then import it to STEPS.

**Comment by zhaolun7** [comment]
My target is to find a way to generate stucture of astrocytes randomly every time. 
**Thanks for replying so fast.**

**Comment by iahepburn** [comment]
Dear @zhaolun7, 
In that case, let me share with you the work of a researcher called Audrey Denizot, who generated astrocyte meshes for STEPS simulations. You may find some useful materials in here: https://adenizot.github.io/code/
