### ISSUE TITLE
A Roadmap Question about the Potential Enhancement for STEPS for the GPU-based Parallelism

### ISSUE THREAD

**Issue by utkuoguzman** [CNS-OIST/STEPS#36]
In your "STEPS 4.0: Fast and memory-effcient molecular simulations of neurons at the nanoscale" 2022 paper, at the "Potential enhancements for STEPS 4" section, you mentioned that:

> "With the importance of GPU-based fat compute nodes in modern HPC clusters, such features will play important roles when STEPS 4 is transitioned to other parallelism schemes."

So I wanted to ask, what is your estimated roadmap for this feature? I am interested in a ballpark estimation answer such as 2025, 2026 or 2027.

Thanks in advance.

**Comment by jlallouette** [comment]
Dear @utkuoguzman,
Thank you for the question. Unfortunately, due to different project priorities, we do not plan on using GPU-based parallelism in the near future.
