### ISSUE TITLE
lacking module after setting up

### ISSUE THREAD

**Issue by FireworkZhao** [CNS-OIST/STEPS#39]
Traceback (most recent call last):
  File ../diffusion.py", line 2, in <module>
    import steps.interface
ModuleNotFoundError: No module named 'steps.interface'

After following the description of importing steps, there are several modules still can't be used while I was trying to reproduce diffusion script from STEPS_Examples(API).

**Comment by tristan0x** [comment]
Hello @FireworkZhao 
Thank you for taking the time to fill this issue.
It looks like the STEPS installation is not visible by your Python interpreter.

* Can you see the `steps` package in the output command `pip list`?
* If your STEPS installation is not installed in one of the _standard_ locations where the Python interpreter looks for packages, you can add this location to the [PYTHONPATH](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH) environment variable.

**Comment by FireworkZhao** [comment]
Thank you for your reply. 
I do can see the STEPS in pip list, the result is showed below:
![pic](https://github.com/CNS-OIST/STEPS/assets/91300417/21652743-6d32-4051-aa83-32ed8a7785cb)

**Comment by iahepburn** [comment]
Hello. I believe (based on the other issue) that you are using version 3.5. steps.interface was not added until 3.6 (https://github.com/CNS-OIST/STEPS/releases/tag/3.6.0)
Is there a reason you are using this older version? Latest version, if building from Github, is actually 5.0.1.

**Comment by FireworkZhao** [comment]
> Hello. You are using version 3.5. steps.interface was not added until 3.6 (https://github.com/CNS-OIST/STEPS/releases/tag/3.6.0) Is there a reason you are using this older version? Latest version, if building from Github, is actually 5.0.1.

Thank you for pointing that out. But when I switch to the master branch and try to build the lastest version, an error seems to occur and I found it hard to fix the problem:
![IMG_1476](https://github.com/CNS-OIST/STEPS/assets/91300417/461d2c59-d1e8-43b4-810b-1d0a7caf9735)
Is there any solution to this situation?

**Comment by iahepburn** [comment]
have you installed mpi4py? Does it show up in pip list?

**Comment by FireworkZhao** [comment]
> have you installed mpi4py? Does it show up in pip list?

Yes, I have
The pip list result is showed as below:
Package         Version
--------------- -------
build           1.2.1
click           8.1.7
Cython          3.0.10
mpi4py          3.1.6
numpy           1.26.4
packaging       24.0
pip             24.0
pip-tools       7.4.1
pyproject_hooks 1.1.0
setuptools      68.2.0
steps           3.5.0
tomli           2.0.1
wheel           0.41.2

**Comment by WeiliangChenOIST** [comment]
closing this as the discussion continues in #40
