### ISSUE TITLE
STEPS Manual link is not available

### ISSUE THREAD

**Issue by mcraveiro** [CNS-OIST/STEPS#5]
Hi STEPS developers,

Apologies for the stream of issues :-) I just tried reading the STEPS manual as per link in the main page[1] but I get a 404[2]:

```
An error has been encountered in accessing this page.

1. Server: steps.sourceforge.net 
2. URL path: /manual_3.0.0/manual_index.html 
3. Error notes: NONE 
4. Error type: 404 
5. Request method: GET 
6. Request query string: NONE 
7. Time: 2017-03-10 10:21:20 UTC (1489141280)
```

Thanks for your time

Marco

[1] http://steps.sourceforge.net/STEPS/documentation.php
[2] http://steps.sourceforge.net/manual_3.0.0/manual_index.html

**Comment by WeiliangChenOIST** [comment]
yes because I was updating the repository and manual files. It should be fine now, the new link to the manual is http://steps.sourceforge.net/manual_3.0/manual_index.html

**Comment by mcraveiro** [comment]
Thanks a lot @WeiliangChenOIST, this link works fine (the link from the documentation page is still 404-ing, its missing a zero, but I guess this is part of your update).

Thanks a lot for the quick responses!

Marco

**Comment by WeiliangChenOIST** [comment]
refresh the webpage, because I think your browser is still reading your cache file instead of the updated version.

**Comment by mcraveiro** [comment]
Aha, gotcha! thanks!
